# Generated by Django 4.1.1 on 2022-12-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image1", models.ImageField(upload_to="post/images")),
                ("image2", models.ImageField(upload_to="post/images")),
                ("image3", models.ImageField(upload_to="post/images")),
                ("proj_title", models.TextField()),
                ("proj_date", models.DateField()),
                ("proj_exp", models.TextField()),
                ("proj_url", models.URLField()),
                ("proj_team", models.TextField()),
            ],
        ),
    ]
