# Generated by Django 4.1.1 on 2022-12-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="proj_stack",
            field=models.TextField(null=True),
        ),
    ]
