# Generated by Django 4.1.1 on 2022-12-14 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0003_post_image4_post_image5"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="proj_date",
        ),
    ]
