# Generated by Django 4.1.1 on 2022-12-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0004_remove_post_proj_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="proj_end",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="proj_start",
            field=models.DateField(null=True),
        ),
    ]
